app/models.py
from datetime import datetime

from app import db


class Translate(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    en = db.Column(db.String(25), unique=True, nullable=False)
    transcription = db.Column(db.String(25), unique=True)
    ru = db.Column(db.String(25), nullable=False)
    repeat_date = db.Column(db.Date, default=datetime.now())

    def __repr__(self):
        return f'<id {self.id}>'


class Song(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), unique=True, nullable=False)
    lyrics = db.Column(db.Text)

    def __repr__(self):
        return f'<{self.title}>'


class EnglishWords(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(50), unique=True, nullable=False)


class RussianWords(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(50), unique=True, nullable=False)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class URLForm(FlaskForm):
    url = StringField("Адрес:", validators=[DataRequired(message="Введите адрес!")])

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from settings import Configuration

db = SQLAlchemy()
migrate = Migrate()


def make_app(config=Configuration):
    app = Flask(__name__)
    app.config.from_object(config)
    db.init_app(app)
    migrate.init_app(app, db)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.api import bp as api_bp
    app.register_blueprint(api_bp)

    return app

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import views

app/api/views.py
from json import loads

from flask import render_template, request, jsonify, Response

from app import db
from app.api import bp
from app.models import Translate, Song
from utils.parse_words import make_en_ru_dict


@bp.route("/api/words/<count>", methods=["GET"])
def words_count(count):
    if isinstance(count, int) or count.isdigit():
        return jsonify({item.en: item.ru for item in Translate.query.all()[:int(count)]})
    else:
        return jsonify({"error": "bad count",
                        "url": f"{request.url}",
                        "correct_url": f"{request.url_root}words/<count>",
                        })


@bp.route("/api/songs/<name>/lyric", methods=["GET"])
def lyric(name):
    song = Song.query.filter_by(title=name)
    if song:
        text = song.first().lyrics
        return jsonify({"title": name,
                        "lyric": text})
    else:
        return jsonify({"error": "bad name",
                        "url": f"{request.url}",
                        })


@bp.route("/api/words/json", methods=["GET", "POST"])
def get_translate():
    if request.method == "POST":
        data = loads(request.get_data())
        words = data.get("words", False)
        error = False
        error_name = ""
        if words:
            for word_en, word_ru in words.items():
                translate = Translate(en=word_en, ru=word_ru)
                try:
                    db.session.add(translate)
                    db.session.commit()
                except Exception as err:
                    error = True
                    error_name = err
                    db.session.rollback()
        if error:
            return {"status": "error", "name": error_name}
        else:
            return {"status": "ok"}
    if request.method == "GET":
        words = request.args
        result = {"words": {}}
        if words:
            for item in words:
                translate = Translate.query.filter_by(en=item).first()
                if translate:
                    result["words"][item] = translate.ru
                else:
                    result["words"][item] = None
            return jsonify(result)


@bp.route("/api/exercise")
def exercise():
    request_page = request.args.get('from_url')
    if request_page:
        content = make_en_ru_dict(request_page)
        template = "url_exercise.html"
    else:
        content = Translate.query.all()
        template = "exercise.html"
    return render_template(template, main_content=content[:20], )


@bp.route("/api/songs")
def songs():
    return jsonify([song.title for song in Song.query.all()])


@bp.route("/api/songs/<name>")
def songs_name(name):
    return jsonify(Song.query.filter_by(songs_name=name).first())

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import views

app/main/views.py
from json import loads

from flask import render_template, redirect, url_for, request, jsonify

from app import db
from app.main import bp
from app.main.forms import URLForm
from app.models import Translate, Song
from utils.parse_words import make_en_ru_dict


@bp.route("/", methods=["GET", "POST"])
def index():
    url_form = URLForm()
    if url_form.validate_on_submit():
        return redirect(url_for('main.exercise', from_url=url_form.url.data))
    return render_template("index.html",
                           url_form=url_form,
                           )


@bp.route("/words/<count>", methods=["GET"])
def words_count(count):
    if isinstance(count, int) or count.isdigit():
        return jsonify({item.en: item.ru for item in Translate.query.all()[:int(count)]})
    else:
        return jsonify({"error": "bad count",
                        "url": f"{request.url}",
                        "correct_url": f"{request.url_root}words/<count>",
                        })


@bp.route("/songs/<name>/lyric", methods=["GET"])
def lyric(name):
    song = Song.query.filter_by(title=name)
    if song:
        text = song.first().lyrics
        return jsonify({"title": name,
                        "lyric": text})
    else:
        return jsonify({"error": "bad name",
                        "url": f"{request.url}",
                        })


@bp.route("/words", methods=["GET"])
def get_words():
    return render_template("words.html")


@bp.route("/words/json", methods=["GET", "POST"])
def get_translate():
    if request.method == "POST":
        data = loads(request.get_data())
        words = data.get("words", False)
        print(data)
        error = False
        error_name = ""
        if words:
            for word_en, word_ru in words.items():
                translate = Translate(en=word_en, ru=word_ru)
                try:
                    db.session.add(translate)
                    db.session.commit()
                except Exception as err:
                    error = True
                    error_name = err
                    db.session.rollback()
        if error:
            return {"status": "error", "name": error_name}
        else:
            return {"status": "ok"}
    if request.method == "GET":
        words = request.args
        result = {"words": {}}
        if words:
            for item in words:
                translate = Translate.query.filter_by(en=item).first()
                if translate:
                    result["words"][item] = translate.ru
                else:
                    result["words"][item] = None
            return jsonify(result)


@bp.route("/exercise")
def exercise():
    request_page = request.args.get('from_url')
    if request_page:
        content = make_en_ru_dict(request_page)
        template = "url_exercise.html"
    else:
        content = Translate.query.all()
        template = "exercise.html"
    return render_template(template, main_content=content[:20], )


@bp.route("/songs")
def songs():
    songs = [song.title for song in Song.query.all()]
    return render_template("songs.html", songs=songs)


@bp.route("/songs/<name>")
def songs_name(name):
    return render_template("song_test.html")

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="English lesson study English">
    <meta name="author" content="sevenamber">
    <link rel="icon" href="data:;base64,=">
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% else %}
                {{ "Учим Английский" }}
            {% endif %}
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS  стили бутстрап-->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Additional CSS  -->
    {% block css %}
    {% endblock %}

    <style>
        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .h-1em {
            height: 1em;
        }
    </style>

</head>
<body>
<main>
    <div class="container-fluid">
        {% block nav %}
            {% include "navigation.html" %}
        {% endblock %}
        <div class="col-md py-3" role="application">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</main><!-- /.container -->
<footer class="p-3 mt-2 border-dark border-top">
    <a class="pl-5" href="mailto:sevenamber@gmail.com">sevenamber@gmail.com</a>
</footer>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% block js %}
{% endblock %}
</body>

app/templates/exercise.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title_content }}</h1>
    <div class="lead">
        {% for item in main_content %}
            <ul class="list-group list-group-horizontal justify-content-between border-0">
                <li class="list-group-item disabled" aria-disabled="true">{{ item.en }}</li>
                {% for _ in range(5) %}
                    <li class="list-group-item">{{ item.ru }}</li>
                {% endfor %}
            </ul>

        {% endfor %}
    </div>
    <p class="lead">
        <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% from "macros.html" import render_field_with_errors, render_field %}
{% block content %}
    <form class="form" action="" method="POST" name="url_form">
        {{ url_form.hidden_tag() }}
        {{ render_field_with_errors(url_form.url, class="form-control", placeholder="URL") }}
        <div id="HelpBlock" class="form-text">
            Введите адрес с текстом на английском языке.
        </div>
    </form>
{% endblock %}

app/templates/its_song.html
Riding on the City of New Orleans,
Illinois Central Monday morning rail
Fifteen cars and fifteen restless riders
Three conductors and twenty-five sacks of mail
All along the southbound odyssey
The train pulls out at Kankakee
Rolls along past houses, farms and fields
Passin' trains that have no names
Freight yards full of old black men
And the graveyards of the rusted automobiles

Good morning America how are you?
So Don't you know me I'm your native son
I'm the train they call The City of New Orleans
I'll be gone five hundred miles when the day is done

Dealin' cards with the old men in the club car
Penny a point ain't no one keepin' score
Won't you pass the paper bag that holds the bottle
Feel the wheels rumblin' 'neath the floor
And the sons of Pullman porters
And the sons of engineers
Ride their fathers' magic carpets made of steel
Mothers with their babes asleep
Are rockin' to the gentle beat
And the rhythm of the rails is all they feel

app/templates/macros.html
{% macro data_split(data) %}
    {% for line in data.split('\n') %}
        {{ line }}<br>
    {% endfor %}
{% endmacro %}

{% macro render_field_with_errors(field) %}
    <p>
        {{ field.label }} {{ field(**kwargs)|safe }}
        {% if field.errors %}
            <ul class="list-unstyled">
                {% for error in field.errors %}
                    <li class="alert alert-danger p-0">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </p>
{% endmacro %}

{% macro render_field(field) %}
    <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

app/templates/navigation.html
{% set menu = [{"url": "main.index", "name": "Главная"},
        {"url": "main.exercise", "name": "Упражнеия"},
        {"url": "main.songs", "name": "Песни"},
        ] %}

<nav class="navbar navbar-expand-lg navbar-light bg-light fs-5">
    <div class="container-fluid py-6">
        <a class="text-decoration-none text-dark fs-3" href="{{ url_for('main.index') }}">Учим Английский</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse nav-divider justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {%- for item in menu -%}
                    <li class="nav-item">
                        {% if request.endpoint == item.url %}
                            {% set active="active" %}
                            {% set curient='aria-current="page"'|safe %}
                        {% endif %}
                        <a class="nav-link {{ active }}" {{ curient }} href="{{ url_for(item.url) }}"
                           title="{{ item.name }}">
                            {{ item.name }}
                        </a>
                    </li>
                {%- endfor -%}
            </ul>
        </div>
    </div>
</nav>

app/templates/song_lyrics.html
{% extends "base.html" %}

{% block css %}
    <link href="{{ url_for('static', filename='css/songs.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="main-content" class="row vh-100">
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/loadPage.js') }}"></script>
{% endblock %}

app/templates/song_test.html
{% extends "base.html" %}

{% block css %}
    <link href="{{ url_for('static', filename='css/songs.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="main-content" class="row vh-100">
    </div>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='js/loadPage.js') }}"></script>
{% endblock %}

app/templates/songs.html
{% extends "base.html" %}

{% block content %}
    <ul class="list-group">
        {% for song in songs %}
            <a class="text-decoration-none" href="{{ url_for("main.songs_name", name = song) }}">
                <li class="list-group-item">{{ song }}</li>
            </a>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/url_exercise.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title_content }}</h1>
    <div class="lead">
        {% for item in main_content %}
            <dl class="list-group-flush">
                <dd><strong>{{ item[0] }}</strong></dd>
                <dt>
                    <ul class="list-group list-group-horizontal justify-content-between">
                        {% for _ in range(5) %}
                            <li class="list-group-item border-0">
                                <button type="button" class="btn btn-secondary" data-word-parent="{{ item[0] }}">
                                    {{ item[1] }}
                                </button>
                            </li>
                        {% endfor %}
                    </ul>
                </dt>
            </dl>
        {% endfor %}
    </div>
    <p class="lead">
        <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
{% endblock %}

app/templates/words.html
{% extends "base.html" %}
{% block content %}
    <div class="from-script border-0">
    </div>
{% endblock %}
{% block js %}
    <script src="{{ url_for('static', filename='js/words.js') }}"></script>
{% endblock %}